module.exports.comments = [
  {
    id: 1,
    name: 'jest',
    profile_photo: 'http://imgur.com/EMkYAVw.jpg',
    message: 'This is the best product that I have every seen',
    date: new Date(),
    product_id: 1,
    user_id: 1,
  },
  {
    id: 2,
    name: 'koa',
    profile_photo: 'http://imgur.com/v3ocr9F.jpg',
    message: 'I love the quality',
    date: new Date(),
    product_id: 1,
    user_id: 2,
  },
  {
    id: 3,
    name: 'ron',
    profile_photo: 'http://imgur.com/lCDjrrC.jpg',
    message: 'Must pledge this product',
    date: new Date(),
    product_id: 1,
    user_id: 3,
  },
  {
    id: 4,
    name: 'posey',
    profile_photo: 'http://imgur.com/UCGBBCF.jpg',
    message: 'This sucks',
    date: new Date(),
    product_id: 1,
    user_id: 4,
  },
  {
    id: 5,
    name: 'wade',
    profile_photo: 'http://imgur.com/gliKr8k.jpg',
    message: 'The idea is good, but the product is bad',
    date: new Date(),
    product_id: 1,
    user_id: 5,
  },
  {
    id: 6,
    name: 'posey',
    profile_photo: 'http://imgur.com/UCGBBCF.jpg',
    message: 'Will you ship to eu or we will have to pay customs?',
    date: new Date(),
    product_id: 2,
    user_id: 1,
  },
  {
    id: 7,
    name: 'koa',
    profile_photo: 'http://imgur.com/v3ocr9F.jpg',
    message: 'Awesome idea, please make this as soon as possible',
    date: new Date(),
    product_id: 2,
    user_id: 2,
  },
  {
    id: 8,
    name: 'posey',
    profile_photo: 'http://imgur.com/UCGBBCF.jpg',
    message: 'Awesome product, please work on it',
    date: new Date(),
    product_id: 2,
    user_id: 4,
  },
  {
    id: 9,
    name: 'koa',
    profile_photo: 'http://imgur.com/v3ocr9F.jpg',
    message: 'This is exciting to see',
    date: new Date(),
    product_id: 2,
    user_id: 5,
  },
  {
    id: 10,
    name: 'ron',
    profile_photo: 'http://imgur.com/lCDjrrC.jpg',
    message: 'What a exciting design',
    date: new Date(),
    product_id: 2,
    user_id: 2,
  },
  {
    id: 11,
    name: 'wade',
    profile_photo: 'http://imgur.com/gliKr8k.jpg',
    message: 'Useless piece of shit',
    date: new Date(),
    product_id: 3,
    user_id: 1,
  },
  {
    id: 12,
    name: 'koa',
    profile_photo: 'http://imgur.com/v3ocr9F.jpg',
    message: 'Looking forward to see product',
    date: new Date(),
    product_id: 2,
    user_id: 1,
  },
  {
    id: 13,
    name: 'ron',
    profile_photo: 'http://imgur.com/lCDjrrC.jpg',
    message: 'LOL',
    date: new Date(),
    product_id: 3,
    user_id: 5,
  },
  {
    id: 14,
    name: 'koa',
    profile_photo: 'http://imgur.com/v3ocr9F.jpg',
    message: 'Great seen ever',
    date: new Date(),
    product_id: 3,
    user_id: 5,
  },
  {
    id: 15,
    name: 'wade',
    profile_photo: 'http://imgur.com/gliKr8k.jpg',
    message: 'Please sell me your idea',
    date: new Date(),
    product_id: 3,
    user_id: 1,
  },
];

module.exports.user = [
  {
    id: 1,
    name: 'jest',
    profile_photo: 'http://imgur.com/EMkYAVw.jpg',
  },
  {
    id: 2,
    name: 'koa',
    profile_photo: 'http://imgur.com/v3ocr9F.jpg',
  },
  {
    id: 3,
    name: 'ron',
    profile_photo: 'http://imgur.com/lCDjrrC.jpg',
  },
  {
    id: 4,
    name: 'posey',
    profile_photo: 'http://imgur.com/UCGBBCF.jpg',
  },
  {
    id: 5,
    name: 'wade',
    profile_photo: 'http://imgur.com/gliKr8k.jpg',
  },
];

module.exports.replies = [
  {
    id: 1,
    name: 'jest',
    profile_photo: 'http://imgur.com/EMkYAVw.jpg',
    message: 'Great!',
    date: new Date(),
    parentCommentId: 1,
  },
  {
    id: 2,
    name: 'wade',
    profile_photo: 'http://imgur.com/gliKr8k.jpg',
    message: 'Fantastic!',
    date: new Date(),
    parentCommentId: 2,
  },
  {
    id: 3,
    name: 'ron',
    profile_photo: 'http://imgur.com/lCDjrrC.jpg',
    message: 'Awesome!',
    date: new Date(),
    parentCommentId: 3,
  },
  {
    id: 4,
    name: 'koa',
    profile_photo: 'http://imgur.com/v3ocr9F.jpg',
    message: 'Wonderful!',
    date: new Date(),
    parentCommentId: 4,
  },
  {
    id: 5,
    name: 'posey',
    profile_photo: 'http://imgur.com/UCGBBCF.jpg',
    message: 'The worst!',
    date: new Date(),
    parentCommentId: 5,
  },
];
