module.exports.comments = [
  {
    id: 1,
    message: 'This is the best product that I have every seen',
    date: '2018-02-21',
    isReply: false,
    replyParentId: 0,
    product_id: 1,
    user_id: 1,
  },
  {
    id: 2,
    message: 'I love the quality',
    date: '2018-02-22',
    isReply: false,
    replyParentId: 0,
    product_id: 1,
    user_id: 2,
  },
  {
    id: 3,
    message: 'Must pledge this product',
    date: '2018-02-23',
    isReply: false,
    replyParentId: 0,
    product_id: 1,
    user_id: 3,
  },
  {
    id: 4,
    message: 'This sucks',
    date: '2018-02-23',
    isReply: false,
    replyParentId: 0,
    product_id: 1,
    user_id: 4,
  },
  {
    id: 5,
    message: 'The idea is good, but the product is bad',
    date: '2018-02-25',
    isReply: false,
    replyParentId: 0,
    product_id: 1,
    user_id: 5,
  },
  {
    id: 6,
    message: 'Will you ship to eu or we will have to pay customs?',
    date: '2018-02-25',
    isReply: false,
    replyParentId: 0,
    product_id: 2,
    user_id: 1,
  },
  {
    id: 7,
    message: 'Awesome idea, please make this as soon as possible',
    date: '2018-02-25',
    isReply: false,
    replyParentId: 0,
    product_id: 2,
    user_id: 2,
  },
  {
    id: 8,
    message: 'Awesome product, please work on it',
    date: '2018-02-25',
    isReply: false,
    replyParentId: 0,
    product_id: 2,
    user_id: 4,
  },
  {
    id: 9,
    message: 'This is exciting to see',
    date: '2018-02-29',
    isReply: false,
    replyParentId: 0,
    product_id: 2,
    user_id: 5,
  },
  {
    id: 10,
    message: 'What a exciting design',
    date: '2018-02-29',
    isReply: false,
    replyParentId: 0,
    product_id: 2,
    user_id: 2,
  },
  {
    id: 11,
    message: 'Useless piece of shit',
    date: '2018-02-29',
    isReply: false,
    replyParentId: 0,
    product_id: 3,
    user_id: 1,
  },
  {
    id: 12,
    message: 'Looking forward to see product',
    date: '2018-03-05',
    isReply: false,
    replyParentId: 0,
    product_id: 2,
    user_id: 1,
  },
  {
    id: 13,
    message: 'LOL',
    date: '2018-03-05',
    isReply: false,
    replyParentId: 0,
    product_id: 3,
    user_id: 5,
  },
  {
    id: 14,
    message: 'Great seen ever',
    date: '2018-03-05',
    isReply: false,
    replyParentId: 0,
    product_id: 3,
    user_id: 5,
  },
  {
    id: 15,
    message: 'Please sell me your idea',
    date: '2018-03-05',
    isReply: false,
    replyParentId: 0,
    product_id: 3,
    user_id: 1,
  },
];

module.exports.user = [
  {
    id: 1,
    name: 'jest',
  },
  {
    id: 2,
    name: 'koa',
  },
  {
    id: 3,
    name: 'ron',
  },
  {
    id: 4,
    name: 'posey',
  },
  {
    id: 5,
    name: 'wade',
  },
];
